### ISSUE TITLE
Original openfxwq repository

### ISSUE THREAD

**Issue by apetresc** [openfoxwq/openfoxwq_dist#1]
Out of curiosity, did you intentionally take down the original openfxwq repo? Any particular reason?

**Comment by ale64bit** [comment]
> Out of curiosity, did you intentionally take down the original openfxwq repo? 

I've made them private for the time being.

> Any particular reason?

In a nutshell, that it's against their ToS and I would prefer to not be sued. Currently I'm hosting the client as a website and native app (distributed via this repo), even though this is still against the ToS. I have also reached to them (unsuccessfully) to try to reach some agreement, hopefully, to allow people without Windows machines to use the third-party client.

More details:
- https://law.stackexchange.com/questions/92457/legality-and-license-choice-for-reverse-engineered-project
- there's a detailed discussion in our Discord. Feel free to join: https://discord.gg/7B7MYWV9

**Comment by apetresc** [comment]
Ah that makes a lot of sense :) Thanks!
